window.portfolioData = {
  projects: {
    toonranks: {
      name: "ToonRanks", type: "Independent product · Nofara LLC", externalLabel: "Open live site", externalUrl: "https://www.toonranks.com/", accent: "#a86bff", mode: "system",
      systemNodes: [
        { id: "overview", short: "TR", label: "Overview", title: "One product, built across every layer.", copy: "ToonRanks is a live ranking and community platform for manga, manhwa, and manhua. Two clients share one protected API, relational data model, media pipeline, identity system, external catalog, and release path.", facts: ["Server-rendered web + native mobile", "Dedicated security and identity boundary", "PostgreSQL, S3, email, and external catalog services"], links: [["Visit ToonRanks", "https://www.toonranks.com/"]] },
        { id: "web", short: "WEB", label: "Web", title: "The public, server-rendered product.", copy: "React Router v7 serves discovery, rankings, series details, comparison, accounts, reading lists, forums, and SEO-sensitive routes. The Node SSR service runs on Railway through Cloudflare-managed DNS, with Railway terminating TLS.", facts: ["React Router v7 SSR", "Railway Node service", "Cloudflare DNS and canonical redirect"], image: "./assets/screens/toonranks-web.jpg", imageAlt: "ToonRanks web rankings interface", imageCaption: "Live web product", links: [["Open web app", "https://www.toonranks.com/"], ["Frontend repository", "https://github.com/trulyepic/toonranks-frontend"]] },
        { id: "mobile", short: "APP", label: "Mobile", title: "The same product, rebuilt for the phone.", copy: "The Expo and React Native client changes navigation, density, touch targets, and session behavior without creating a separate product. Rankings, votes, lists, forum activity, avatars, and identity remain shared with the website.", facts: ["React Native + Expo", "TanStack Query", "SecureStore token lifecycle"], image: "./assets/screens/toonranks-mobile.jpg", imageAlt: "ToonRanks mobile series detail interface", imageCaption: "Android product", links: [["Mobile repository", "https://github.com/trulyepic/toon-rank-mobile-v2"], ["Google Play", "https://play.google.com/store/apps/details?id=com.toonranks.mobile"]] },
        { id: "security", short: "SEC", label: "Security", title: "A dedicated trust boundary protects every write.", copy: "Authentication and request protection are explicit parts of the product: bcrypt password hashing, signed JWT access tokens, hashed and revocable mobile refresh tokens, Google OAuth verification, reCAPTCHA, role guards, rate limiting, CORS controls, and upload validation.", facts: ["JWT + bcrypt + hashed refresh tokens", "Google OAuth + reCAPTCHA", "RBAC, rate limits, CORS, and media validation"] },
        { id: "api", short: "API", label: "Backend", title: "The shared product core.", copy: "FastAPI coordinates rankings, voting, reading lists, forum relationships, moderation, notifications, issue reports, account workflows, and media. Both clients use the stable api.toonranks.com contract.", facts: ["FastAPI + async SQLAlchemy", "Typed route and schema modules", "Health endpoint and guarded admin workflows"], links: [["Backend repository", "https://github.com/trulyepic/toonranks-backend"]] },
        { id: "data", short: "RDS", label: "Amazon RDS", title: "Managed PostgreSQL is the relational source of truth.", copy: "Amazon RDS for PostgreSQL stores the shared product model: users, series, category votes, lists, forum trees, reactions, reports, refresh-token records, read state, and notifications.", facts: ["Amazon RDS for PostgreSQL", "Async SQLAlchemy + asyncpg", "Shared state across web and mobile"] },
        { id: "aws", short: "S3", label: "AWS media", title: "Media leaves the application server.", copy: "AWS S3 stores series covers, avatars, and forum uploads. FastAPI owns upload validation and object lifecycle, then persists the public object URL with the related product record.", facts: ["Series covers", "User avatars", "Forum images and GIFs"] },
        { id: "email", short: "MAIL", label: "Email", title: "Account recovery runs outside the request UI.", copy: "The backend sends verification and password-reset messages through authenticated SMTP. Purpose-specific signed tokens expire and password-reset tokens are bound to the current password hash.", facts: ["Verification and reset flows", "Authenticated SMTP with TLS", "Purpose-bound, expiring tokens"] },
        { id: "catalog", short: "EXT", label: "AniList", title: "External context enters through a review workflow.", copy: "An admin-only integration queries AniList GraphQL for manga metadata, discovery, and comparison signals. Imported titles enter a private review queue and remain hidden until approval.", facts: ["AniList GraphQL API", "Admin and contributor role guards", "Approval before publication"] },
        { id: "delivery", short: "OPS", label: "Delivery", title: "Independent services, one release path.", copy: "Web and API services deploy independently on Railway while mobile has its own verification pipeline. Pull requests run linting, tests, builds, and browser checks; merges trigger service deployments with prior Railway deployments available for rollback.", facts: ["Frontend, backend, and mobile CI", "Railway auto-deploys", "Deployment logs and rollback path"] }
      ]
    },
    mcp: {
      name: "MCP Design Foundations", type: "Internal AI systems · Universal Music Group", externalLabel: "Private organization project", externalUrl: "", accent: "#82d7c5", mode: "protocol",
      protocolNodes: [
        { id: "overview", short: "MCP", label: "Overview", title: "Trusted design context through a narrow boundary.", copy: "This internal service gives agents access to published Design Foundations references without exposing the systems behind them. It is a deliberately small, read-only adapter built for useful context, clear ownership, and controlled access.", facts: ["Read-only by design", "Enterprise identity", "Source-grounded responses"] },
        { id: "identity", short: "ID", label: "Identity", title: "Every request proves who and what it represents.", copy: "Microsoft Entra JWT validation checks the exact issuer, audience, tenant, and JWKS chain, then requires an approved app role or delegated scope. Invalid or ambiguous identity fails closed.", facts: ["Exact issuer and audience validation", "App role or delegated scope", "No copied-token workflow"] },
        { id: "integrity", short: "SHA", label: "Bundle integrity", title: "Only a verified reference bundle becomes context.", copy: "The published bundle is checked against its manifest, index, and schema before use. Byte size, SHA-256, freshness, and fingerprint checks make drift visible and preserve a known-good fallback.", facts: ["Manifest and schema checks", "SHA-256 and byte-size verification", "Last-valid-bundle behavior"] },
        { id: "tools", short: "API", label: "Bounded tools", title: "Three tools, each with an explicit job.", copy: "The MCP surface stays intentionally small: check confirms availability, search finds relevant guidance, and retrieve returns the requested source material. The service does not invent design decisions or silently widen its authority.", facts: ["check() availability", "search() references", "retrieve() source material"] },
        { id: "provenance", short: "SRC", label: "Provenance", title: "Answers remain attached to their source.", copy: "Retrieved guidance carries the reference context needed to understand where it came from. Version and fingerprint metadata keep agent output attributable to the published Design Foundations material.", facts: ["Source-grounded retrieval", "Bundle version and fingerprint", "Traceable reference context"] },
        { id: "operations", short: "OPS", label: "Operations", title: "A secure service still has to be operable.", copy: "Connection guidance, Codex setup, DEV validation, deployment status, TLS details, runbooks, and protected-resource metadata turn the adapter into a service that other engineers can adopt and support.", facts: ["Repeatable Codex setup", "DEV validation and runbooks", "Deployment and TLS visibility"] }
      ]
    },
    habits: {
      name: "Habit Tracker", type: "Independent full-stack product", externalLabel: "View source", externalUrl: "https://github.com/trulyepic/habit-tracker-frontend", accent: "#9fcf74", mode: "quest",
      questNodes: [
        { id: "overview", short: "START", label: "Habit Arena", title: "Daily habits become a playable progression loop.", copy: "Habit Tracker reframes routine work as quests: check-ins build streaks, award XP, advance titles, unlock achievements, and damage daily or weekly bosses. Guest mode makes the loop immediate, while accounts preserve server-backed progression.", facts: ["Guest and authenticated play", "XP, titles, achievements, and cosmetic skins", "Daily and weekly encounter loops"], image: "./assets/screens/habit-arena.jpg", imageAlt: "Habit Arena guest dashboard", imageCaption: "Current WIP interface", links: [["Frontend repository", "https://github.com/trulyepic/habit-tracker-frontend"], ["Backend repository", "https://github.com/trulyepic/habit-tracker-backend"]] },
        { id: "experience", short: "UI", label: "Player experience", title: "The interface makes consistency feel consequential.", copy: "React turns ordinary habit actions into readable game feedback: boss health, streak combos, reward chests, level-up scenes, achievement notices, recovery quests, and skin unlocks. Effects remain subordinate to the next useful action.", facts: ["React 19 + Vite", "Accessible quest, profile, and claim views", "Lazy-loaded reward and level-up moments"] },
        { id: "contract", short: "GQL", label: "GraphQL contract", title: "The client asks; the domain answers explicitly.", copy: "Apollo Client communicates with a Django and Graphene API using session credentials. Mutations return explicit result states such as claimed, already claimed, or incomplete so the interface does not have to infer what happened.", facts: ["Apollo Client + Graphene", "Session-based authenticated requests", "Explicit mutation reason contracts"] },
        { id: "rules", short: "BOSS", label: "Progression rules", title: "Rewards are protected by backend-owned rules.", copy: "Daily and weekly objectives rotate deterministically from managed catalogs. Reward claims are idempotent, duplicate check-ins cannot award XP twice, and streak recovery is modeled as a deliberate domain flow rather than a client-side animation.", facts: ["Idempotent daily and weekly claims", "Deterministic boss and objective rotation", "Backend-owned XP and achievement progression"] },
        { id: "data", short: "DATA", label: "Persistence", title: "One product supports two levels of commitment.", copy: "Guest progress is stored locally for a no-friction first session. Authenticated players use Django models backed by SQLite during local development and PostgreSQL on Railway, preserving habits, check-ins, profiles, claim state, and achievement progress.", facts: ["Local guest persistence", "Django relational models", "PostgreSQL on Railway"] },
        { id: "quality", short: "CI", label: "Verification", title: "The critical journey is exercised as a journey.", copy: "Playwright covers login, quest creation, check-in, claims, and the distinction between deactivation and deletion. Backend checks and frontend browser flows run in GitHub Actions, keeping the GraphQL contract and product behavior visible during change.", facts: ["Playwright end-to-end flows", "Frontend and backend CI", "Behavior-focused regression coverage"], links: [["Frontend source", "https://github.com/trulyepic/habit-tracker-frontend"], ["Backend source", "https://github.com/trulyepic/habit-tracker-backend"]] }
      ]
    },
    career: {
      name: "Career Journey", type: "Experience · Universal Music Group", externalLabel: "Open resume", externalUrl: "./assets/resume/kenneth-nwoye-software-engineering-resume.pdf", accent: "#f28b75", mode: "career",
      careerNodes: [
        { id: "overview", short: "PATH", label: "Overview", period: "2015 — now", title: "Operations taught me what software has to survive.", copy: "My route into engineering started inside the workflows software is supposed to support: metadata, financial operations, partner delivery, release deadlines, and production incidents. That history shapes how I build systems now: clear contracts, traceable actions, and practical tools people can operate after launch.", facts: ["10+ years at Universal Music Group", "4+ years in professional software development", "Backend depth with product and operational context"] },
        { id: "operations", short: "OPS", label: "Operations", period: "2015 — 2021", title: "I learned the business from the production floor.", copy: "Across metadata, financial support, mobile content, data integration, and digital release management, I worked where accuracy and deadlines meet. I investigated defects, analyzed XML and delivery data, coordinated label releases, and helped resolve issues across territories and partners.", facts: ["Metadata and financial operations", "XML analysis and data integration", "Release coordination across US, Canada, and Mexico"] },
        { id: "engineering", short: "ENG", label: "Software engineering", period: "2022 — 2025", title: "Operational knowledge became engineering leverage.", copy: "I moved into software engineering and contributed to decomposing a legacy Java monolith into Spring Boot services. The work covered REST and SOAP integrations, Hibernate service layers, PostgreSQL schemas and migrations, React interfaces, code review, refactoring, and production troubleshooting.", facts: ["Java · Spring Boot · Hibernate", "REST, SOAP, and PostgreSQL", "Legacy modernization and production support"] },
        { id: "product", short: "P&S", label: "Product & Services", period: "2025 — now", title: "Today I build product workflows end to end.", copy: "In Product & Services, I develop Python, Django, GraphQL, PostgreSQL, and React/TypeScript systems. Recent work includes approval workflows, product chat, rules management, notifications, audit capabilities, confidential-asset safeguards, identity improvements, and reliability work across engineering, QA, product, and platform teams.", facts: ["Python · Django · GraphQL", "React · TypeScript · PostgreSQL", "Auditability, security, observability, and controlled recovery"] },
        { id: "ai", short: "AI", label: "AI systems", period: "Current practice", title: "AI is treated as an engineering system, not a shortcut.", copy: "I help shape internal AI workflows through MCP services, reusable skills, agent guidance, and source-grounded documentation. The focus is bounded access, dependable context, repeatable setup, and workflows that make teams faster without making their systems less trustworthy.", facts: ["MCP services and trust boundaries", "Reusable skills, agents, and documentation", "Source-grounded and permission-aware workflows"] },
        { id: "education", short: "EDU", label: "Education", period: "2008 — 2019", title: "Business context first, software depth second.", copy: "I earned a BS in Business Administration and later an MS in Information Technology focused on software development. That combination still shows up in the work: understand the operating problem, then build the technical system around it.", facts: ["MS Information Technology: Software Development · SNHU", "4.0 graduate GPA", "BS Business Administration: Management · University of Baltimore"] },
        { id: "credentials", short: "CERT", label: "Credentials", period: "Professional foundation", title: "Cloud and Java fundamentals back the experience.", copy: "Formal credentials complement the production work and long-term engineering progression. They are supporting evidence, not the center of the story.", facts: ["AWS Certified Cloud Practitioner · valid through 2027", "Oracle Certified Associate, Java SE 8 Programmer", "Continuous delivery through testing, review, and documentation"] }
      ]
    }
  }
};
